name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Hello world
        run: echo Hello, world!

      - name: List Kubernetes nodes
        run: kubectl get nodes

      - name: List Kubernetes pods
        run: kubectl get pods -A

      - name: List services
        run: kubectl get svc -A
