name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Hello world
        run: echo Hello, world!

      - name: List Kubernetes nodes
        run: kubectl get nodes

      - name: List Kubernetes pods
        run: kubectl get pods -A

      - name: List services
        run: kubectl get svc -A

      - name: List AWS S3 buckets
        run: aws s3 ls

      # -------------------------
      # TERRAFORM SECTION
      # -------------------------

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: terraform
        run: |
          terraform plan \
            -var="bucket_name=my-unique-bucket-123456-soparla"

      - name: Terraform Apply
        working-directory: terraform
        run: |
          terraform apply -auto-approve \
            -var="bucket_name=my-unique-bucket-123456-soparla"

      - name: List AWS S3 buckets
        run: aws s3 ls